# ----------------------------------------------------------------------------
# Name     : .bash_profile
# Function : user startup-file for bash
# Origin   : created by /env/common/bin/login_files_change
#
# Note     : Please do not edit this file until you have read the
#            site policy file for dot-files: /etc/home/README
#
# ----------------------------------------------------------------------------
[ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
