alias rpsxtreme="python3 ~/Documents/rpsXtreme/game/rpsxtreme.py"
alias rpsxserver="python3 ~/Documents/rpsXtreme/server/rpsxserver.py"
alias rpsxclient="python3 ~/Documents/rpsXtreme/client/rpsxclient.py"
alias assar@pajver="ssh assar@155.4.151.254"
alias assar@pajver+x="ssh -x assar@155.4.151.254"
alias g++11="reset && g++ -std=c++11 -Wextra -Wall -Werror"
alias g++11="reset && g++ -std=c++11 -Wextra -Wall -Werror"
alias g++17="reset && g++ -std=c++17 -Wextra -Wall -Werror"
alias compile="reset && g++17"
alias no="~/no"